name: Build and deploy website to GitHub Pages


on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Create Roby environment
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Install Ruby gems
        run: cd website && bundle install

      - name: Install npm dependencies
        run: cd website && npm ci

      - name: Build website
        run: cd website && bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Archive build artifact
        run: tar --directory website/_site/ -cvf "$RUNNER_TEMP/website-build.tar" .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ${{ runner.temp }}/website-build.tar
          if-no-files-found: error


  deploy:
    runs-on: ubuntu-20.04
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@v2
